
name: Create crate dist
on:
  push:
    tags:
      - '**'

jobs:
  crate-dist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create crate dist
        uses: projg2/crate-dist-action@v1
        with:
          directories: harper-ls
          dist-filename: harper-0.41.0-crates.tar.xz
          run-cargo-update: false

